# Site settings
title: BTAS
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#LIVE baseurl: "" # the subpath of your site, e.g. /blog/
#LIVE url: "" # the base hostname & protocol for your site
baseurl: "/btas/" # the subpath of your site, e.g. /blog/
url: "https://robertbasden.github.io" # the base hostname & protocol for your site
twitter_username: rob_basden
github_username:  robertbasden

# Build settings
markdown: kramdown
